import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { initializeTestEnvironment, assertFails, assertSucceeds } from '@firebase/rules-unit-testing';
import { getDoc, doc } from 'firebase/firestore';
import { persist, db as admin } from '../functions/index.js';
if (!process.env.FIRESTORE_EMULATOR_HOST) throw new Error('Ejecutar únicamente con el emulador de Firestore.');
const projectId=process.env.GCLOUD_PROJECT || 'demo-agenda-cv';
const env=await initializeTestEnvironment({projectId,firestore:{rules:await readFile(new URL('../firestore.rules',import.meta.url),'utf8')}});
after(()=>env.cleanup());
test('dos reservas simultáneas aceptan una sola y no exponen datos del cliente',async()=>{
  const uid='owner-concurrency';
  const parent=admin.doc(`propietarios/${uid}`);
  await parent.set({config:{horaInicio:'08:00',horaFin:'18:00',duracionTurno:60,diasHabiles:[0,1,2,3,4,5,6]}});
  const future=new Date(Date.now()+7*86400000).toISOString().slice(0,10);
  const turn={clienteNombre:'Cliente ficticio',clienteTel:'000',fecha:future,hora:'09:00',estado:'pendiente'};
  const results=await Promise.allSettled([persist(uid,turn,true),persist(uid,turn,true)]);
  assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
  const id=results.find(r=>r.status==='fulfilled').value.id;
  const publicData=(await parent.collection('ocupados').doc(id).get()).data();
  assert.deepEqual(Object.keys(publicData).sort(),['duracion','fecha','hora']);
  const privateData=(await parent.collection('turnos').doc(id).get()).data();
  assert.equal(privateData.cancelCode,undefined);
  assert.equal(privateData.cancelHash.length,64);
  const anonymous=env.unauthenticatedContext().firestore();
  const stranger=env.authenticatedContext('someone-else').firestore();
  const owner=env.authenticatedContext(uid).firestore();
  await assertSucceeds(getDoc(doc(anonymous,`propietarios/${uid}/ocupados/${id}`)));
  await assertFails(getDoc(doc(anonymous,`propietarios/${uid}/turnos/${id}`)));
  await assertFails(getDoc(doc(stranger,`propietarios/${uid}/turnos/${id}`)));
  await assertSucceeds(getDoc(doc(owner,`propietarios/${uid}/turnos/${id}`)));
});
